backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "cruise"
    label: "Cruises"
    folder: "src/content/cruises" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "cruise" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Destination", name: "destination", widget: "string" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "End Date", name: "endDate", widget: "datetime" }
      - { label: "Date Range (Display Text)", name: "dateRange", widget: "string", hint: "e.g., June 15 - June 29, 2025" }
      - { label: "Featured Image", name: "imageUrl", widget: "image" }
      - { label: "Gallery Images", name: "galleryImages", widget: "list", field: { label: "Image", name: "image", widget: "image" }, required: false }
      - { label: "Short Description", name: "shortDescription", widget: "text" }
      - { label: "Description", name: "body", widget: "markdown" }
      - label: "Itinerary"
        name: "itinerary"
        widget: "list"
        fields:
          - { label: "Day", name: "day", widget: "number" }
          - { label: "Date", name: "date", widget: "string", required: false }
          - { label: "Port", name: "port", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
      - label: "Amenities"
        name: "amenities"
        widget: "list"
        field: { label: "Amenity", name: "amenity", widget: "string" }
      - { label: "Affiliate Link", name: "affiliateLink", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list", field: { label: "Category", name: "category", widget: "string" }, required: false }
      - { label: "Featured", name: "isFeatured", widget: "boolean", default: false }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Introduction", name: "introduction", widget: "text", required: false }
          - label: "FAQ"
            name: "faq"
            widget: "list"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }

# Optional: Global settings file
#  - name: "settings"
#    label: "Settings"
#    files:
#      - file: "src/content/settings.json"
#        label: "Site Settings"
#        name: "settings"
#        fields:
#          - { label: "Site Title", name: "siteTitle", widget: "string" }
#          - { label: "Site Description", name: "siteDescription", widget: "string" }
#          - { label: "Logo", name: "logo", widget: "image", required: false }

